apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: pokemons.kd.dev
spec:
 group: kd.dev
 names:
  plural: pokemons
  singular: pokemon
  kind: Pokemon
  shortNames:
  - poke
  - mon
 scope: Namespaced
 versions:
 - name: v1
   served: true
   storage: true
   schema:
    openAPIV3Schema:
     type: object
     properties:
      spec:
       type: object
       properties:
        type:
         type: string
        name: 
         type: string
        desc:
         type: string
        gen:
         type: string
