apiVersion: v1
kind: Service
metadata:
        name: bluegreen-svc-test
spec:
        selector:
                app: bluegreen-test
                color: blue
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
