apiVersion: apps/v1
kind: Deployment
metadata:
        name: rolling-update-deployment
spec:
        replicas: 5
        selector: 
                matchLabels:
                        app: rolling
        template:
                metadata:
                        labels:
                                app: rolling
                spec:
                        containers:
                        - name: nginx
                          image: nginx:stable
                          ports:
                          - containerPort: 80
